ALTER TABLE analyzed_wordforms ADD INDEX multipleLemmataAnalysisId (multiple_lemmata_analysis_id);
ALTER TABLE analyzed_wordforms ADD INDEX awfId (analyzed_wordform_id ASC);
ALTER TABLE corpusId_x_documentId ADD INDEX documentIdIndex (document_id);
ALTER TABLE corpusId_x_documentId ADD INDEX corpusIdIndex (corpus_id);
ALTER TABLE documents ADD INDEX documentIdIndex (document_id ASC);
ALTER TABLE lemmata ADD INDEX glossIndex (gloss ASC);
ALTER TABLE lemmata ADD INDEX modernLemmaIndex (modern_lemma ASC);
ALTER TABLE lemmata ADD INDEX lemmaPartOfSpeechIndex (lemma_part_of_speech ASC);
ALTER TABLE multiple_lemmata_analyses ADD INDEX multipleLemmataAnalysisPartNumberIndex (part_number ASC);
ALTER TABLE multiple_lemmata_analysis_parts ADD INDEX multipleLemmataAnalysisPartIdIndex (multiple_lemmata_analysis_part_id ASC);
ALTER TABLE token_attestations ADD INDEX analyzedWordformIdIndex (analyzed_wordform_id);
ALTER TABLE token_attestations ADD INDEX documentIdIndex (document_id);
ALTER TABLE token_attestations ADD INDEX startPosIndex (start_pos);
ALTER TABLE token_attestations ADD INDEX endPosIndex (end_pos);
ALTER TABLE token_attestation_verifications ADD INDEX verifiedByIndex (verified_by ASC);
ALTER TABLE type_frequencies ADD INDEX wordformIdIndex (wordform_id);
ALTER TABLE type_frequencies ADD INDEX documentIdIndex (document_id);
ALTER TABLE wordforms ADD INDEX wordformIdIndex (wordform_id ASC);
ALTER TABLE wordform_groups ADD INDEX wordformGroupIdIndex (wordform_group_id ASC);